# Generated by Django 4.2 on 2025-07-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional detection metadata'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='report_data',
            field=models.JSONField(blank=True, default=dict, help_text='Comprehensive report data'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='report_generated',
            field=models.BooleanField(default=False, help_text='Whether detailed report was generated'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='temporal_consistency',
            field=models.FloatField(blank=True, help_text='Temporal consistency score', null=True),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='threshold_used',
            field=models.FloatField(blank=True, help_text='Detection threshold used', null=True),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, help_text='User IP address', null=True),
        ),
    ]
